development:
  auth0_domain: dev-y83fonahojtfiitm.us.auth0.com
  auth0_client_id: L3vgdqQ3Cm2HCQW6Cqp5R9HHbIrtzXZ5
  auth0_client_secret: xA3f7pXqQBbO7ZO6-i3Fu6z1NER-zNflUShsSWL5NsvD_s1fbF3OoXrHGNUOuIPp
  callback_path: "/auth/auth0/callback"

production:
  auth0_domain: "<%= ENV['AUTH0_DOMAIN'] %>"
  auth0_client_id: "<%= ENV['AUTH0_CLIENT_ID'] %>"
  auth0_client_secret: "<%= ENV['AUTH0_CLIENT_SECRET'] %>"
  callback_path: "/auth/auth0/callback"