default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: elle_marko_development

test:
  <<: *default
  database: elle_marko_test

production:
  <<: *default
  database: elle_marko_production